// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUUHPeJ03Zom3WTxeVPAUPjDtjUhn1BQQ',
    appId: '1:522364690237:web:5867d71a35e3655c34ef54',
    messagingSenderId: '522364690237',
    projectId: 'flutter-udem-2024-360ee',
    authDomain: 'flutter-udem-2024-360ee.firebaseapp.com',
    storageBucket: 'flutter-udem-2024-360ee.appspot.com',
    measurementId: 'G-MNZM2DXY0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmEMqdAh-WTlRgidZCmhNpJbPAdvaM2QM',
    appId: '1:522364690237:android:0422486dd302eb0034ef54',
    messagingSenderId: '522364690237',
    projectId: 'flutter-udem-2024-360ee',
    storageBucket: 'flutter-udem-2024-360ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARYGi1Nk5RWTlh85ykHRU3Z37-uYkSeNk',
    appId: '1:522364690237:ios:79a06a8a66d58db134ef54',
    messagingSenderId: '522364690237',
    projectId: 'flutter-udem-2024-360ee',
    storageBucket: 'flutter-udem-2024-360ee.appspot.com',
    iosBundleId: 'com.example.practica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARYGi1Nk5RWTlh85ykHRU3Z37-uYkSeNk',
    appId: '1:522364690237:ios:79a06a8a66d58db134ef54',
    messagingSenderId: '522364690237',
    projectId: 'flutter-udem-2024-360ee',
    storageBucket: 'flutter-udem-2024-360ee.appspot.com',
    iosBundleId: 'com.example.practica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUUHPeJ03Zom3WTxeVPAUPjDtjUhn1BQQ',
    appId: '1:522364690237:web:4ae94d45d41d614334ef54',
    messagingSenderId: '522364690237',
    projectId: 'flutter-udem-2024-360ee',
    authDomain: 'flutter-udem-2024-360ee.firebaseapp.com',
    storageBucket: 'flutter-udem-2024-360ee.appspot.com',
    measurementId: 'G-GKGLHBGG3M',
  );
}
