// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxQlAtz4h0qZgyv8MfglEpFyJChEoieB0',
    appId: '1:2773394026:web:e43c1da98dbc2469f9a013',
    messagingSenderId: '2773394026',
    projectId: 'auth-firebase-c70eb',
    authDomain: 'auth-firebase-c70eb.firebaseapp.com',
    storageBucket: 'auth-firebase-c70eb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA48ojlRo7njD8eZfpqHgYUmDrmNaOc17M',
    appId: '1:2773394026:android:1a1bf78a195069edf9a013',
    messagingSenderId: '2773394026',
    projectId: 'auth-firebase-c70eb',
    storageBucket: 'auth-firebase-c70eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5Y8fP01a5U2fq1jqpcvC-zoUxhtbm3xo',
    appId: '1:2773394026:ios:308276739cbe5b28f9a013',
    messagingSenderId: '2773394026',
    projectId: 'auth-firebase-c70eb',
    storageBucket: 'auth-firebase-c70eb.appspot.com',
    iosBundleId: 'com.example.flutterApplication10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5Y8fP01a5U2fq1jqpcvC-zoUxhtbm3xo',
    appId: '1:2773394026:ios:308276739cbe5b28f9a013',
    messagingSenderId: '2773394026',
    projectId: 'auth-firebase-c70eb',
    storageBucket: 'auth-firebase-c70eb.appspot.com',
    iosBundleId: 'com.example.flutterApplication10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxQlAtz4h0qZgyv8MfglEpFyJChEoieB0',
    appId: '1:2773394026:web:3d0261e7d51e0650f9a013',
    messagingSenderId: '2773394026',
    projectId: 'auth-firebase-c70eb',
    authDomain: 'auth-firebase-c70eb.firebaseapp.com',
    storageBucket: 'auth-firebase-c70eb.appspot.com',
  );
}
